"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var LInkedLIst_1 = require("./LInkedLIst");
var CharactersCollection_1 = require("./CharactersCollection");
var NumbersCollection_1 = require("./NumbersCollection");
var numbersCollection = new NumbersCollection_1.NumbersCollection([-1, 34, 64, 3, 786, 231212, 32, 64, -12, 56 - 5645]);
numbersCollection.sort();
console.log(numbersCollection.data);
var characters = new CharactersCollection_1.CharactersCollection("Xaayb");
characters.sort();
console.log(characters.data);
var linkedList = new LInkedLIst_1.LinkedList();
linkedList.add(10);
linkedList.add(6);
linkedList.add(18);
linkedList.add(19);
linkedList.add(120);
linkedList.sort();
linkedList.print();
